jms_security_extra:
    secure_all_services: false
    expressions: true


security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MANAGER:       [ROLE_USER]
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username        # fos_user.user_provider.username_email does not seem to work (OAuth-spec related ("username + password") ?)
    firewalls:

        public:
            # since anonymous is allowed users will not be forced to login
            pattern:   ^/.*
            form_login:
                #login_path: fos_user_security_login
                check_path: /check
                provider: fos_userbundle
                remember_me: true
                failure_handler: security.authentication.failure_handler
                success_handler: security.authentication.success_handler
                default_target_path:            /
                failure_path:    /login

            remember_me:
                key:         %secret%
                lifetime: 604800
                path:     /
                domain:   ~
                user_provider: fos_userbundle
            anonymous: true
            logout: false

        #login:
        #    pattern:  ^/login$
        #    security: false
        #secured_area:
        # ...
        #    logout:
        #      path:   logout # a route called logout
        #      target: login
